name: Build Sidewalk samples and tests
on:
  workflow_call:
    inputs:
      change_nrf_revision:
        description: 'change revision of nrf in west.yml to `main`'
        default: false
        required: false
        type: boolean

jobs:
  prep_matrixes:
    runs-on: ubuntu-latest
    steps:
      - id: nrf52
        run: |
          echo "platform=nrf52840dk_nrf52840" >> $GITHUB_OUTPUT
      - id: nrf53
        run: |
          echo "platform=nrf5340dk_nrf5340_cpuapp" >> $GITHUB_OUTPUT
    outputs:
      supported_platforms: ${{ toJson(steps.*.outputs.platform)}}

  build_samples:
    needs: prep_matrixes
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.prep_matrixes.outputs.supported_platforms) }}
        subset: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    env:
      MAX_SUBSETS: 12

    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: change_nrf_revision
        if: ${{ inputs.change_nrf_revision }}
        run: |
          python3 -m pip install -r scripts/ci/requirements.txt
          python3 scripts/ci/replace_nrf_revision_in_west.py internal_west.yml

      - name: Reconfigure west
        run: |
          cp -r ../sdk-sidewalk /workdir/internal_sidewalk
          cd /workdir
          west config manifest.path internal_sidewalk
          west config manifest.file internal_west.yml
          west update --narrow -o=--depth=1
          ln -s internal_sidewalk sidewalk

      - name: Twister build samples
        run: |
          /workdir/zephyr/scripts/twister --platform ${{ matrix.platform }} --testsuite-root /workdir/sidewalk/samples/ --inline-logs --overflow-as-errors --show-footprint --footprint-from-buildlog -vvv --build-only --subset ${{ matrix.subset }}/${{ env.MAX_SUBSETS }}
          mkdir -p subsets/${{ matrix.platform }}_${{ matrix.subset }}_of_${{ env.MAX_SUBSETS }}
          cp twister-out/twister.json subsets/${{ matrix.platform }}_${{ matrix.subset }}_of_${{ env.MAX_SUBSETS }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: sample-artifacts
          path: |
            subsets
            twister-out/**/*sidewalk*/build.log
            twister-out/**/*sidewalk*/zephyr/.config
            twister-out/**/*sidewalk*/zephyr/runners.yaml
            twister-out/**/*sidewalk*/zephyr/zephyr.elf
            twister-out/**/*sidewalk*/zephyr/zephyr.hex
            twister-out/**/*sidewalk*/zephyr/merged.hex
            twister-out/**/*sidewalk*/zephyr/merged_domains.hex
            twister-out/**/*sidewalk*/zephyr/*.dts
            twister-out/**/*sidewalk*/zephyr/dfu_application.zip

  build_and_run_ut_x86:
    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: change_nrf_revision
        if: ${{ inputs.change_nrf_revision }}
        run: |
          python3 scripts/ci/replace_nrf_revision_in_west.py internal_west.yml

      - name: Reconfigure west
        run: |
          cp -r ../sdk-sidewalk /workdir/internal_sidewalk
          cd /workdir
          west config manifest.path internal_sidewalk
          west config manifest.file internal_west.yml
          west update --narrow -o=--depth=1
          ln -s internal_sidewalk sidewalk

      - name: Build test artifacts for
        run: /workdir/zephyr/scripts/twister --platform native_posix --platform unit_testing --testsuite-root /workdir/sidewalk/tests/ --inline-logs --overflow-as-errors -vvv

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests-x86_result
          path: |
            twister-out/twister.xml
            twister-out/**/handler.log
            twister-out/**/device.log

  build_manual_tests:
    needs: prep_matrixes
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.prep_matrixes.outputs.supported_platforms)}}
        subset: [1, 2, 3, 4]
    env:
      MAX_SUBSETS: 4

    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: change_nrf_revision
        if: ${{ inputs.change_nrf_revision }}
        run: |
          python3 scripts/ci/replace_nrf_revision_in_west.py internal_west.yml

      - name: Reconfigure west
        run: |
          cp -r ../sdk-sidewalk /workdir/internal_sidewalk
          cd /workdir
          west config manifest.path internal_sidewalk
          west config manifest.file internal_west.yml
          west update --narrow -o=--depth=1
          ln -s internal_sidewalk sidewalk

      - name: Build test artifacts
        run: |
          /workdir/zephyr/scripts/twister --platform ${{ matrix.platform }} --testsuite-root /workdir/sidewalk/tests/manual --inline-logs --overflow-as-errors -vvv --build-only --subset ${{ matrix.subset }}/${{ env.MAX_SUBSETS }}
          mkdir -p subsets/${{ matrix.platform }}_${{ matrix.subset }}_of_${{ env.MAX_SUBSETS }}
          mv twister-out/twister.json subsets/${{ matrix.platform }}_${{ matrix.subset }}_of_${{ env.MAX_SUBSETS }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests-manual-artifacts
          path: |
            subsets
            twister-out/**/*sidewalk*/build.log
            twister-out/**/*sidewalk*/zephyr/.config
            twister-out/**/*sidewalk*/zephyr/runners.yaml
            twister-out/**/*sidewalk*/zephyr/zephyr.elf
            twister-out/**/*sidewalk*/zephyr/zephyr.hex
            twister-out/**/*sidewalk*/zephyr/merged.hex
            twister-out/**/*sidewalk*/zephyr/merged_domains.hex
            twister-out/**/*sidewalk*/zephyr/*.dts
            twister-out/**/*sidewalk*/zephyr/dfu_application.zip

  build_tests:
    needs: prep_matrixes
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.prep_matrixes.outputs.supported_platforms)}}
        subset: [1, 2, 3, 4, 5]
    env:
      MAX_SUBSETS: 5

    runs-on: ubuntu-latest
    container:
      image: nordicplayground/nrfconnect-sdk:main
      options: --cpus 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: change_nrf_revision
        if: ${{ inputs.change_nrf_revision }}
        run: |
          python3 scripts/ci/replace_nrf_revision_in_west.py west.yml

      - name: Reconfigure west
        run: |
          cp -r ../sdk-sidewalk /workdir/internal_sidewalk
          cd /workdir
          west config manifest.path internal_sidewalk
          west config manifest.file internal_west.yml
          west update --narrow -o=--depth=1
          ln -s internal_sidewalk sidewalk

      - name: Build test artifacts for
        run: |
          /workdir/zephyr/scripts/twister --platform ${{ matrix.platform }} --testsuite-root /workdir/sidewalk/tests/functional --testsuite-root /workdir/sidewalk/tests/unit_tests --testsuite-root /workdir/sidewalk/tests/validation --inline-logs --overflow-as-errors -vvv --prep-artifacts-for-testing --package-artifacts PACKAGE_ARTIFACTS_${{ matrix.platform }}_${{ matrix.subset }}.tar.bz2 --subset ${{ matrix.subset }}/${{ env.MAX_SUBSETS }}
          rm -rf twister-out
          tar -xf PACKAGE_ARTIFACTS_${{ matrix.platform }}_${{ matrix.subset }}.tar.bz2
          mkdir -p subsets/${{ matrix.platform }}_${{ matrix.subset }}_of_${{ env.MAX_SUBSETS }}
          mv twister-out/*.json subsets/${{ matrix.platform }}_${{ matrix.subset }}_of_${{ env.MAX_SUBSETS }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tests-dut-artifacts
          path: |
            twister-out
            subsets
