name: Build Docker image for CI

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/ci/Docker/*'

  schedule:
    - cron: "0 1 * * 0"

  workflow_dispatch:

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          docker build scripts/ci/Docker/ --tag Nordic-sidewalk-ci:latest
          docker push Nordic-sidewalk-ci:latest
