name: On PR action
on:
  pull_request:

jobs:
  Run_Configuration:
    runs-on: ubuntu-latest
    outputs:
      NRF_revision: ${{ steps.config.outputs.NRF_revision }}
    steps:
      - name: Read body of PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{github.repository}}/pulls/${{github.event.number}} --jq '.body' > pr_body.md

      - uses: chrisdickinson/setup-yq@latest
      - name: Get configuration
        id: config
        shell: bash {0}
        run: |
          cat pr_body.md

          csplit pr_body.md /\`\`\`yaml/1
          csplit xx01 /\`\`\`/
          mv xx00 configuration.yaml

          revision=$(yq '.Github_actions.NRF_revision' xx00)
          if [ $? != 0 ]; then
            echo "NRF_revision=main" >> $GITHUB_OUTPUT;
          else
            echo "NRF_revision=$revision" >> $GITHUB_OUTPUT;
          fi;

      - name: print nrf revision
        run: |
          echo ${{ steps.config.outputs.NRF_revision }}

  verify_PR:
    uses: ./.github/workflows/validate_code_style.yml
    with:
      reference_commit: ${{ github.event.pull_request.base.sha }}

  save_pr_number:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number to file
        run: |
          echo "${{ github.event.number }}" > PR_number

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PR_number
          path: |
            PR_number

  build_samples:
    needs: Run_Configuration
    uses: ./.github/workflows/samples_build.yml
    with:
      nrf_revision: ${{needs.Run_Configuration.outputs.NRF_revision}}

  build_and_run_tests:
    needs: Run_Configuration
    uses: ./.github/workflows/run_tests.yml
    with:
      nrf_revision: ${{needs.Run_Configuration.outputs.NRF_revision}}
