name: Publish release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build_samples:
    uses: ./.github/workflows/samples_build.yml

  build_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install default-jre graphviz -y
          curl -sSL https://github.com/plantuml/plantuml/releases/download/v1.2023.13/plantuml-1.2023.13.jar --output /usr/local/bin/plantuml.jar

      - name: Build documentation
        run: cd doc; bash ./build_local.sh

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: |
            doc/build

  publish_release:
    needs: [build_documentation, build_samples]
    permissions: write-all
    name: Create release page
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+.[0-9]+.[0-9]+$ ]]; then
              echo "prerelease=false" >> $GITHUB_OUTPUT
          else
              echo "prerelease=true" >> $GITHUB_OUTPUT
          fi

      - name: prepare artifacts
        run: |
          mkdir package
          cd artifacts
          shopt -s extglob
          for f in !(*.zip) ; do zip -r $f.zip $f/; mv $f.zip ../package; done

      - name: Upload artifacts to release page
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: package/*.zip
          file_glob: true
          overwrite: true
          prerelease: ${{ steps.check-tag.outputs.prerelease }}
