name: On Commit action

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:

jobs:
  Build_samples_and_tests:
    uses: nrfconnect/sdk-sidewalk/.github/workflows/common_build_samples.yml@main

  Run_tests_on_DUT:
    needs: Build_samples_and_tests
    uses: nrfconnect/sdk-sidewalk/.github/workflows/common-run-ut-on-dut.yml@main
