name: On PR action
on:
  pull_request:
    branches:
      - main

jobs:
  ValidateCodeCompliance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          python3 -m pip install -r ./scripts/ci/requirements.txt && sudo apt install uncrustify

      - name: Check formatting
        run: |
          python3 ./scripts/ci/verify_formatting.py -d -s . -c ./scripts/ci/formatter_cfg.yml

      - name: Check license
        run: |
          python3 ./scripts/ci/verify_license.py -s . -c ./scripts/ci/license.yml

  Save_PR_number:
    runs-on: ubuntu-latest
    steps:
      - name: save PR number to file
        run: |
          echo "${{ github.event.number }}" > PR_number
  
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: PR_number
          path: |
            PR_number

  Build_samples_and_tests:
    needs: ValidateCodeCompliance
    uses: RobertGalatNordic/sdk-sidewalk/.github/workflows/common_build_samples.yml@main
  
  Run_tests_on_DUT:
    needs: Build_samples_and_tests
    uses: RobertGalatNordic/sdk-sidewalk/.github/workflows/common_run_UT_on_DUT.yml@main
