name: Publish test results
on:
  workflow_call:

jobs:
  test-results:
    name: "Publish Unit Tests Results"
    runs-on: ubuntu-22.04
    steps:
      - name: Download dut test artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/dut
          name: tests-dut_result
      - name: Download x86 test artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/x86
          name: tests-x86_result

      - name: Merge Test Results
        run: |
          pip3 install junitparser junit2html
          junitparser merge artifacts/*/twister.xml junit.xml
          junit2html junit.xml junit.html

      - name: Upload Unit Test Results in HTML
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: HTML Unit Test Results
          if-no-files-found: ignore
          path: |
            junit.html

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Unit Test Results
          files: "**/*twister.xml"
          comment_mode: off
