name: Build and run DUT tests
on:
  workflow_call:
    inputs:
      nrf_revision:
        type: string
        required: false
        default: "main"
      subset:
        description: ""
        required: true
        type: number
      max_subsets:
        description: ""
        type: number
        required: true
      target_board:
        description: "target board for tests"
        type: string
        required: true
      run_tests:
        description: ""
        required: false
        type: boolean
        default: true

jobs:
  build_dut_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nrfconnect/sdk-sidewalk:main
      options: --cpus 2
    defaults:
      run:
        shell: nrfutil toolchain-manager launch --install-dir /root/ncs bash -- {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: sidewalk

      - name: update NRF
        run: |
          cd sidewalk &&  git rev-parse HEAD > /workdir/sidewalk_hash; cd ..
          west init -m https://github.com/nrfconnect/sdk-nrf --mr main .
          if [[ "${{inputs.nrf_revision}}" =~ "pull/" ]]; than
            git fetch ncs ${{inputs.nrf_revision}}:PR-branch; git checkout PR-branch;
          else
            git fetch ncs; git checkout ${{inputs.nrf_revision}};
          fi
          west config manifest.group-filter +sidewalk
          west update -n -o=--depth=1 --path-cache /workdir/
          cd sidewalk; git checkout `cat /workdir/sidewalk_hash`; rm -rf /workdir/sidewalk_hash
      - name: Install Python dependencies
        run: |
          python3 -m pip install -r nrf/scripts/requirements.txt -r zephyr/scripts/requirements.txt -r sidewalk/scripts/ci/requirements.txt

      - name: Build DUT test artifacts
        run: |
          source zephyr/zephyr-env.sh
          west twister --platform ${{inputs.target_board}} --testsuite-root sidewalk --filter runnable --shuffle-tests --shuffle-tests-seed 123 --inline-logs --overflow-as-errors -vvv --prep-artifacts-for-testing --package-artifacts PACKAGE_ARTIFACTS_${{ inputs.subset }}.tar.bz2 --subset ${{ inputs.subset }}/${{ inputs.max_subsets }}

      - name: save build artifacts
        uses: actions/cache@v4
        with:
          path: PACKAGE_ARTIFACTS_${{ inputs.subset }}.tar.bz2
          key: DUT_artifacts_${{inputs.target_board}}_${{ inputs.subset }}_${{ github.sha }}_${{ github.run_id }}

  run_dut_ut:
    needs: [build_dut_tests]
    if: ${{ fromJson(inputs.run_tests) }}
    continue-on-error: true
    runs-on: [self-hosted, linux, x64, "${{inputs.target_board}}"]
    container:
      image: ghcr.io/nrfconnect/sdk-sidewalk:main
      options: --cpus 2 --privileged
      volumes:
        - /dev:/dev
        - /run/udev:/run/udev
    defaults:
      run:
        shell: nrfutil toolchain-manager launch --install-dir /root/ncs bash -- {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: sidewalk

      - name: update NRF
        run: |
          cd sidewalk &&  git rev-parse HEAD > /workdir/sidewalk_hash; cd ..
          west init -m https://github.com/nrfconnect/sdk-nrf --mr main .
          if [[ "${{inputs.nrf_revision}}" =~ "pull/" ]]; than
            git fetch ncs ${{inputs.nrf_revision}}:PR-branch; git checkout PR-branch;
          else
            git fetch ncs; git checkout ${{inputs.nrf_revision}};
          fi
          west config manifest.group-filter +sidewalk
          west update -n -o=--depth=1 --path-cache /workdir/
          cd sidewalk; git checkout `cat /workdir/sidewalk_hash`; rm -rf /workdir/sidewalk_hash

      - name: Install Python dependencies
        run: |
          python3 -m pip install -r sidewalk/scripts/ci/requirements.txt

      - name: Get build artifacts
        uses: actions/cache/restore@v4
        id: cache
        with:
          path: PACKAGE_ARTIFACTS_${{ inputs.subset }}.tar.bz2
          key: DUT_artifacts_${{inputs.target_board}}_${{ inputs.subset }}_${{ github.sha }}_${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Fail on missing artifacts
        if: steps.cache.outputs.cache-hit != 'true'
        run: exit 1

      - name: Unwrap artifacts
        run: |
          tar -xf PACKAGE_ARTIFACTS_${{ inputs.subset }}.tar.bz2

      - name: Run Tests
        run: |
          source zephyr/zephyr-env.sh
          west twister --no-clean -vvv --inline-logs --test-only --hardware-map /__w/hardware_map.yaml --device-testing -T sidewalk --retry-failed 2 --west-flash="--recover,--erase"

      - name: rename_twister_xml_report
        run: |
          mv twister-out/twister.xml twister-out/${{inputs.target_board}}_${{ inputs.subset }}_twister.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tests-dut_result_${{inputs.target_board}}_${{ inputs.subset }}
          path: |
            twister-out/${{inputs.target_board}}_${{ inputs.subset }}_twister.xml
            twister-out/**/handler.log
            twister-out/**/device.log
            twister-out/**/zephyr.hex
            twister-out/**/zephyr.elf
