name: Publish release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+.*'

jobs:
  build:
    permissions: write-all
    name: Add documentaiton as asset
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cd doc; ./build_local.sh && zip -r documentation.zip build/html/*

      - name: Get artifacts from commit
        uses: dawidd6/action-download-artifact@v2
        with:
          commit: ${{github.sha}}
          workflow: on_commit.yml
          path: build
      - name: Pack build artifacts
        run: |
          zip -r build_artifacts.zip build/sample*
          zip -r test_artifacts.zip build/tests*

      - name: Upload documentation binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: doc/documentation.zip
          asset_name: documentation.zip
          tag: ${{ github.ref }}
          overwrite: true
      
      - name: Upload build binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build_artifacts.zip
          asset_name: twister_build_artifacts.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload test binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: test_artifacts.zip
          asset_name: twister_test_artifacts.zip
          tag: ${{ github.ref }}
          overwrite: true
        