name: verify new ncs version

# The docker images are build at midnight, lets give it some time to build, and update in nordicplayground
on:
  schedule:
    - cron: "0 1 * * 1-6"

jobs:
  build_samples_and_tests:
    uses: nrfconnect/sdk-sidewalk/.github/workflows/common-build.yml@main
    with:
      change_nrf_revision: true

  run_tests:
    needs: build_samples_and_tests
    uses: nrfconnect/sdk-sidewalk/.github/workflows/common-run-tests.yml@main

  publish_test_summary:
    if: ${{ always() }}
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          comment_mode: off
          files: |
            artifacts/**/twister.xml
