name: verify new ncs version

on:
  schedule:
    - cron: "0 1 * * 1-6"

jobs:
  build_samples_and_tests:
    uses: ./.github/workflows/common-build_and_run.yml
    with:
      change_nrf_revision: true

  publish_test_results:
    needs: [build_samples_and_tests]
    uses: ./.github/workflows/publish_test_results.yml
